// <auto-generated />
using System;
using ComputationalLinguistics.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputationalLinguistics.DAL.Migrations
{
    [DbContext(typeof(ComputationalLinguisticsContext))]
    [Migration("20211009082355_RemovedFrequency")]
    partial class RemovedFrequency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TextFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FilePath" }, "IFilePath");

                    b.ToTable("TextFiles");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Content" }, "IContent");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.Property<Guid>("TextFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Seek")
                        .HasColumnType("int");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TextFileId", "Seek");

                    b.HasIndex(new[] { "TextFileId", "Seek" }, "ITextFileId");

                    b.HasIndex(new[] { "WordId" }, "IWordId");

                    b.ToTable("WordsInText");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TextFile", "TextFile")
                        .WithMany()
                        .HasForeignKey("TextFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TextFile");

                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
