// <auto-generated />
using System;
using ComputationalLinguistics.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputationalLinguistics.DAL.Migrations
{
    [DbContext(typeof(ComputationalLinguisticsContext))]
    [Migration("20211207201935_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TagInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("bit");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TagName" }, "ITagName");

                    b.ToTable("TagsInfo");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TextFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileAnnotationPath")
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FilePath" }, "IFilePath");

                    b.ToTable("TextFiles");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("TagInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TagInfoId");

                    b.HasIndex(new[] { "Content", "TagInfoId" }, "IWordInfo");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NextWordInTextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OffSet")
                        .HasColumnType("int");

                    b.Property<Guid>("TextFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextWordInTextId");

                    b.HasIndex(new[] { "TextFileId", "OffSet" }, "ITextFileId");

                    b.HasIndex(new[] { "WordId" }, "IWordId");

                    b.ToTable("WordsInText");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.Word", b =>
                {
                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TagInfo", "TagInfo")
                        .WithMany()
                        .HasForeignKey("TagInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagInfo");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.WordInText", "NextWordInText")
                        .WithMany()
                        .HasForeignKey("NextWordInTextId");

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TextFile", "TextFile")
                        .WithMany()
                        .HasForeignKey("TextFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextWordInText");

                    b.Navigation("TextFile");

                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
