// <auto-generated />
using System;
using ComputationalLinguistics.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputationalLinguistics.DAL.Migrations
{
    [DbContext(typeof(ComputationalLinguisticsContext))]
    [Migration("20211126214020_AddedTagPairsToWordInText")]
    partial class AddedTagPairsToWordInText
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TagInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TagName" }, "ITagName");

                    b.ToTable("TagsInfo");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TagPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NextId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrentId");

                    b.HasIndex("NextId");

                    b.ToTable("TagPairs");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TextFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileAnnotationPath")
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FilePath" }, "IFilePath");

                    b.ToTable("TextFiles");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Content", "Tag" }, "IWordInfo");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.Property<Guid>("TextFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OffSet")
                        .HasColumnType("int");

                    b.Property<Guid>("TagPairId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TextFileId", "OffSet");

                    b.HasIndex("TagPairId");

                    b.HasIndex(new[] { "TextFileId", "OffSet" }, "ITextFileId");

                    b.HasIndex(new[] { "WordId" }, "IWordId");

                    b.ToTable("WordsInText");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.TagPair", b =>
                {
                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TagInfo", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TagInfo", "Next")
                        .WithMany()
                        .HasForeignKey("NextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Current");

                    b.Navigation("Next");
                });

            modelBuilder.Entity("ComputationalLinguistics.DAL.Core.Entities.WordInText", b =>
                {
                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TagPair", "TagPair")
                        .WithMany()
                        .HasForeignKey("TagPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.TextFile", "TextFile")
                        .WithMany()
                        .HasForeignKey("TextFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputationalLinguistics.DAL.Core.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagPair");

                    b.Navigation("TextFile");

                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
